# Introduction

The Neexdzii Kwah (Upper Bukley River) and Widzin Kwah (Morice River) are some of the most degraded areas of salmon habitat in the Skeena watershed. In partnership with the Morice Water Monitoring Trust and A Rocha, both members of the Upper Bulkley Round Table, a low-tech, process-based, watershed restoration project will be implemented that builds upon previous work in the region (funded in-part by BC’s Healthy Watersheds Initiative) to engage with local land users to stabilize streambanks, rebuild riparian structure in degraded areas of importance to salmon and ecosystem function, and remove current barriers for migrating juvenile salmon. This process-based approach relies on assisting natural river corridor processes over time, learning what works on river reach and basin scales, a high degree of outreach and collaboration with interest holders and regulators, and the use of simple – cost-effective – non-engineered structural additions of natural materials to restore river processes (i.e., let the river do the work).

The purpose of this document is to outline watershed restoration initiatives for the Upper Bulkley River and Morice River. The Upper Bulkley and Morice watersheds are located in the traditional territory of the Wet'suwet'en First Nation, and are home to the Bulkley River and Morice River. Both the Bulkley River, a major tributary of the Skeena River, and the Morice River, a major tributary of the Bulkley River, are known for their world-class steelhead and salmon fishing. The Morice and upper Bulkley watersheds are critical habitat for salmon and steelhead, and are important areas for the Wet'suwet'en First Nation. Additionally, this area plays a pivotal role in the local economy and is a favored destination for outdoor recreation. These watersheds are facing a number of challenges, including habitat degradation, water quality issues, and climate change. The purpose of this document is to outline watershed restoration initiatives for the Upper Bulkley and Morice watersheds which can be actionable in year 2 and 3 of the project.

## Wet'suwet'en

Wet'suwet'en hereditary territory covers an area of 22,000km^2^ including the Bulkley River watershed, Zymoetz River watershed, Morice River watershed and portions of the Nechako River watershed. The Wet'suwet'en people are a matrilineal society organized into the Gilseyhu (Big Frog), Laksilyu (Small Frog), Tsayu (Beaver clan), Gitdumden (Wolf/Bear) and Laksamshu (Fireweed) clans. Within each of the clans there are are a number of kin-based groups known as Yikhs or House groups. The Yikh is a partnership between the people and the territory. Thirteen Yikhs with Hereditary Chiefs manage a total of 38 distinct territories upon which they have jurisdiction. Within a clan, the head Chief is entrusted with the stewardship of the House territory to ensure the Land is managed in a sustainable manner. Inuk Nu'at'en (Wet'suwet'en law) governing the harvesting of fish within their lands are based on values founded on thousands of years of social, subsistence and environmental dynamics. The Yintahk (Land) is the centre of life as well as culture and it's management is intended to provide security for sustaining salmon, wildlife, and natural foods to ensure the health and well-being of the Wet'suwet'en [@officeofthewetsuweten2013Wetsuweta; @OfficeWetsuwet2021; @flnrord2017NaturalResourcea]. There are a total of six first nation bands that encompass the Wet'suwet'en. These are: Wet'suwet'en, Ts'il Kaz Koh, Hagwilget Village, Nee-Tahi-Buhn Band, Skin Tyee and Witset [@Wetsuweten2022a].
