# Methods

## Collaborative GIS Environment
Geographical Information Systems are essential for understanding restoration plans and the reasons they are required. Without the ability to visualize the landscape and the data that is used to make decisions it is difficult to
conduct and communicate the need for restoration, the details of past and future plans as well as and the potential results of physical works. 

<br>

To facilitate the planning and implementation of restoration activities in the Neexdzii Kwah (and elsewhere within the Widzin Kwah Water Sustainability Project area), a collaborative GIS environment (titled `restoration_wedzin_kwa`) has been established using [QGIS](https://qgis.org/en/site/) and [Mergin Maps](https://merginmaps.com/) (source code [here](https://github.com/MerginMaps). This environment is intended to be a space where project team members can access and view and contribute to the amalgamation of background spatial data and the development of restoration as well as monitoring for the project. The collaborative GIS environment allows users to view, edit, and analyze shared up to date spatial data on personal computers in an office setting as well as phones and tablets in the field. At the time of reporting, the environment was being used to develop and share maps, conduct spatial analyses, communicate restoration plans to stakeholders as well as to provide a central place to store methodologies and tools for conducting field assessments on standardized pre-developed digital forms. The platform can also be used to track the progress of restoration activities and monitor changes in the landscape over time helping encourage the record keeping of past and future restoration activities in a coordinated manner.

<br>

The shared QGIS project was created using scripts currently kept in [`dff-2022`](https://github.com/NewGraphEnvironment/dff-2022) with the precise calls to project creation scripts tracked in the `project_creation_and_permissions.txt` document kept in the main project directory. Information about how GIS project creation and update scripts function can be viewed [here](https://github.com/NewGraphEnvironment/dff-2022/tree/master/scripts/qgis) with outcomes of their use summarized below:

  - download and clip user specified layers from the [BC Data Catalougue](https://catalogue.data.gov.bc.ca/) as well as data layers stored in custom Amazon Web Services buckets for an area of interest defined by a list of watershed groups and load to a geopackage called `background_layers.gpkg` stored in the main directory of the project.  An additional `lateral_habitat.tiff` layer is also clipped to the user defined area and loaded to the project.
  - A project directory is created to hold the spatial data and `QGIS` project information (ie. layer symbology and naming conventions, metadata, etc.).  
  - Metadata for individual project spatial layers is kept in the `rfp_tracking` table within the `background_layers.gpkg` along with tables related to user supplied stream width/gradient inputs to `bcfishpass` to model potentially high value habitat that is accessible to fish species of interest. 

```{r qris, eval=FALSE}
## QRis
# [QGIS Riverscapes Studio](https://qris.riverscapes.net/) (QRis) is a free plugin for QGIS that helps you digitize your riverscape data. QRis is a great planning tool for helping users with spatial representation of riverscapes. 
# 
# QRis has two distinct types of features:
#   
#   * Static: These are features that are relatively permanent, such as the valley bottom.
#   * Dynamic: These are features that change over time, such as the active channel.
# 
# QRis will be a useful tool for digitizing the upper Wetzin'kwa river and prioritizing restoration sites. To start using QRis, follow the instructions for [getting started](https://qris.riverscapes.net/getting-started/).
```

## Past Restoration Initiative Identification
Information regarding past restoration initiatives, prescriptions and activities is an important component of the restoration planning process. A wealth of information is present for the Neexdzii Kwah however it is located in many different locations and not always spatially represented.  To address this, a comprehensive review of past restoration activities is underway. This review included a review of the literature, interviews with local experts, and a review of the restoration prescriptions and activities that have been conducted in the Neexdzii Kwah. For information regarding relatively recent restoration efforts such as physical works conducted through Healthy Watersheds Initiative, representatives from the Morice Watershed Monitoring Trust amalgamated all information located on physical drives and either provided emails with the data attached or provided links to the data for the study team for download and review.  This information was then subsequently downloaded and re-uploaded to a `OneDrive` folder for the study team to access.  Additional data was also sourced from the [Skeena Salmon Data Centre](https://data.skeenasalmon.info/) using the application programming interface to their [CKAN](https://ckan.org/features/api) database.  

## Future Restoration Site Selection

### Fish Passage
At the time of writing, extensive work related to fish passage restoration planning was underway in the Neexdzii Kwah watershed
as well as other areas of the greater Skeena watershed.  Methodology for this work is presented in @irvine2023BulkleyWatershed,
@irvine2022BulkleyRiver and @irvine2021BulkleyRiver.  Although these references detail work related to linear connectivity 
(ie. upstream/downstream) there is ongoing work related to lateral connnectivity (ie. floodplain connectivity) with methodology
realted to disconnections due to the railway documented in `bcfishpass` [@norris2024smnorrisbcfishpass] [here](https://github.com/smnorris/bcfishpass/tree/main/model/03_habitat_lateral).  
The results of this analysis and future analysis incorporating major roadways as well (currently under development) will 
be added to the shared QGIS project and used to inform future restoration activity prioritization.

### Local Knowledge for Riparian Area and Erosion Protection Site Selection
To facilitate project activities in the short term - the project team will select among some known areas of riparian 
removal and bank erosion where landowners are amenable to project activities including installation of cattle exclusion 
fencing and riparian planting in the next two fiscal years.


### Evaluation of Historic and Current Imagery
Evaluation of historic and current imagery to understand and quantify morphological changes in the Neexdzii Kwah and its major tributaries over time and guide future restoration efforts. This will require that the study team acquire, georeference, archive and analyze historic imagery for the Neexdzii Kwah watershed and compare with an analysis of recent LiDAR data to quantify historic changes in stream morphology resulting in loss of quantity and quality of water and fish habitat.  Through this process we hope to highlight areas of historic dredging, realignment, and floodplain disconnections due to infrastructure that have degraded watershed health and fish habitat.


### Delineation of Areas of High Fisheries Values
Spatially delineate areas of high fisheries values based on modelled and known spawning and rearing habitat for fish species of interest.  
Project team members have mentioned that there was work done in the past to spatially delineate areas of high value habitat
for chinook and potentially sockeye salmon. This data will hopefully be aquired.  Additionally background literature includes some decriptions of traditional Wet'suwet'en
Fisheries sites which can be spatialized for the project.

### Parameter Ranking to Select Future Restoration Sites 
Analysis of background and current data will be used to inform priority ranking criteria used to select sites for restoration activities in the long term. **Although this has not yet been conducted** - included in this process can be:

  - GIS and user input parameters were selected based on project team meetings and review of available spatial information to rank future restoration sites.  Whenever possible standardized names for layers (schema and table) and fields were used to facilitate the reproducibility of similiar analysis on other or updated datasets, both by ourselves and by others.  

  

