# Recommendations

Developing comprehensive restoration planning for the Neexdzii Kwah watershed will help ensure that the restoration activities address the underlying drivers of the degradation necessitating restoration. Understanding of the drivers of the degredation will require intensive field assessments, the use of GIS that incorperates all data possible, incorperation of background information and amalgamation of local knowledge. The following recommendations are provided to try to ensure that the restoration activities are effective and address the underlying drivers of the degredation.  At the time of writing this can be considered a partial list as the project is still in development and the recommendations are subject to change as the project progresses.  The recommendations to date are as follows:



1. Spatially represent past prescriptions in the watershed where information is available. @ncfdc1998 prescriptions have been extracted from their report and are presented in Table \@ref(tab:tab-ncfdc-1998-pres).  These prescriptions can be loaded into the collaborative GIS project and reviewed collaboratively to understand historic priority ranking, reevaluate the utility of the work 30 years later and help feed into adaptive management where restoration actions were persued.

2. Spatially represent historic fisheries sites presented in  Table \@ref(tab:tab-hist-sites) so the option is available that potential areas of restoration can be ranked according to their proximity to these sites.

3. Spatially delineate areas of high fisheries values based on known spawning and rearing habitat for fish species of interest. Where data gaps exist - develop study plans to understand where this high value habitat is and quantify its value for fish species of interest through standardized methodologies such as Fish and Fish Habitat Assessment Procedures [@johnstonFishHabitatAssessment1996].  For known spawning and rearing locations, load reviewed data into `bcfishpass` using the `user_habitat_classification.csv` file located [here](https://github.com/smnorris/bcfishpass/blob/main/data/user_habitat_classification.csv).  Information can then be pulled into the collaborative GIS project and queried to facilitate priority ranking of areas of high fisheries values.

4.   Acquire, georeference, archive (within SKT) and analyze historic aerial imagery for the Neexdzii Kwah watershed and compare with recent orthoimagery and/or LiDAR data to quantify historic changes in stream morphology resulting in loss of quantity and quality of water and fish habitat while highlighting areas of historic dredging, realignment, and floodplain disconnections due to infrastructure, to guide future restoration efforts. Script all analysis when possible to facilitate reproducibility and sharing of the analysis.

5.   Further refine parameters (GIS and user input) to select future restoration sites and develop a ranking system for each of the parameters to aid in the prioritization of future sites. Whenever possible, develop and share open-source workflows to extract ranking parameters from datasets unaltered from their original sources to facilitate the reproducibility of similiar analysis on other or updated datasets, both by ourselves and by others.

6. Continue to develop and document data management workflows to leverage existing established data storage systems to retrieve data from and load too and build capacity for all interested to do the same.  Established data storage systems include the [BC Data Catalogue](https://catalogue.data.gov.bc.ca/), the [Skeena Salmon Data Centre](https://data.skeenasalmon.info/), [NuSEDS-New Salmon Escapement Database System](https://open.canada.ca/data/en/dataset/c48669a3-045b-400d-b730-48aafe8c5ee6) (example of `.html` file that can be downloaded here and opened in browser such as Chrome - double click - https://github.com/NewGraphEnvironment/restoration_wedzin_kwa_2024/tree/main/memos) and [bcfishpass](https://github.com/smnorris/bcfishpass/tree/main/data) 

7.   Develop criteria for minimal setbacks required for cattle exclusion and riparian restoration based on the ecosystem services provided by the riparian area and the potential for the area to provide habitat for fish species of interest. Utilize established standards when possible such as the [Riparian Areas Protection Regulation](https://www2.gov.bc.ca/gov/content/environment/plants-animals-ecosystems/fish/aquatic-habitat-management/riparian-areas-regulation) and the [Riparian Management Area Guidebook](https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/silviculture/silvicultural-systems/silviculture-guidebooks/riparian-management-area-guidebook) [@ministryofforests1995RiparianManagement].

8.  Amalgamate drone acquired ortho-imagery gathered for sites in the Neexdzii Kwah watershed, store as Cloud Optimized Geotiffs on a cloud service provider and link to the imagery via the collaborative GIS project.  Orthoimagery has been gathered for past monitoring of historic restoration sites as well as part of fish passage restoration planning efforts.

9. Amalgamate past effectiveness monitoring information and present within online reporting to facilitate leveraging foward
of this information through sharing and review.  

10. Link historic and potential future sites to the freshwater atlas using the linear feature id of stream segments and conduct
watershed drainage area analysis for individual stream segments (or portions of steram segments) so that this area can be tied to other GIS and user input parameters.  Functions kept in [fwapg](https://github.com/smnorris/fwapg), [fwapgr](https://github.com/poissonconsulting/fwapgr), [fwatlasbc](https://github.com/poissonconsulting/fwatlasbc) and custom function developed for this project can be used. 
Results from this can be compared to other methods for determining project setbacks from the high water mark such as the [Riparian Areas Protection Regulation](https://www2.gov.bc.ca/gov/content/environment/plants-animals-ecosystems/fish/aquatic-habitat-management/riparian-areas-regulation) and the [Riparian Management Area Guidebook](https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/silviculture/silvicultural-systems/silviculture-guidebooks/riparian-management-area-guidebook) [@ministryofforests1995RiparianManagement].

11. Develop a monitoring plan for the Neexdzii Kwah watershed restoration works that incorporates and can leverage past monitoring methodology and data but and also includes an updated monitoring schedule, monitoring objectives, and methods. Methodology using Watershed Restoration Procedures - Routine effectiveness evaluation procedures and riparian inventory techniques ([LMH25](https://www.for.gov.bc.ca/hfd/pubs/Docs/Lmh/Lmh25/Lmh25_ed2_(2010).pdf) - percent cover by structural stage, species composition, etc.) could be utilized using pre-built digital forms served to field teams from the collaborative GIS project.
