
fpr_db_query(fpr_dbq_lscols(schema = 'whse_basemapping', table = 'fwa_watershed_groups_poly'))

wshd <- fpr_db_query(query= "SELECT DISTINCT watershed_group_code, watershed_group_name
  FROM whse_basemapping.fwa_watershed_groups_poly")

# knitr::kable(wshd) Run in Rmarkdown script elsewhere

datapasta::tribble_paste()

tfpr_xref_wshd_names <- tibble::tribble(
  ~watershed_group_code,        ~watershed_group_name,
                 "LILL",                   "Lillooet",
                 "MILL",             "Milligan Creek",
                 "DEAD",              "Deadman River",
                 "TSEA",                 "Tsea River",
                 "COTR",           "Cottonwood River",
                 "TASR",               "Taseko River",
                 "EUCH",            "Euchiniko River",
                 "NASR",                 "Nass River",
                 "ALBN",              "Alberni Inlet",
                 "NASC",              "Nascall River",
                 "PARA",                "Parsnip Arm",
                 "KITR",              "Kitimat River",
                 "UKEC",        "Upper Kechika River",
                 "FOXR",                  "Fox River",
                 "ATNA",              "Atnarko River",
                 "LSTR",        "Lower Stikine River",
                 "HOMA",             "Homathko River",
                 "SLOC",               "Slocan River",
                 "SALR",               "Salmon River",
                 "DEAL",                 "Dease Lake",
                 "BARR",           "Barrington River",
                 "LNRS",    "Lower Nechako Reservoir",
                 "DOGC",                  "Dog Creek",
                 "CLAY",                  "Clayoquot",
                 "TUYR",                 "Tuya River",
                 "KUMR",             "Kumowdah River",
                 "UNTH", "Upper North Thompson River",
                 "JENR",             "Jennings River",
                 "UNUR",                 "Unuk River",
                 "TAHR",              "Tahltan River",
                 "NAKR",               "Nakina River",
                 "LFRT",    "Lower Fort Nelson River",
                 "TOAD",                 "Toad River",
                 "COMX",                      "Comox",
                 "UISR",          "Upper Iskut River",
                 "ATLL",                 "Atlin Lake",
                 "CHUK",           "Chukachida River",
                 "GLAR",               "Gladys River",
                 "GUIC",              "Guichon Creek",
                 "TWAC",                 "Twan Creek",
                 "EUCL",             "Euchiniko Lake",
                 "BABL",                "Babine Lake",
                 "WILL",               "Willow River",
                 "STUR",               "Stuart River",
                 "KEEC",               "Keecha Creek",
                 "LRAN",     "Little Rancheria River",
                 "SIML",          "Similkameen River",
                 "SHER",              "Sheslay River",
                 "TESR",               "Teslin River",
                 "NIMP",             "Nimpkish River",
                 "CRYL",                   "Cry Lake",
                 "NAHR",               "Nahlin River",
                 "KTSU",                 "Kitasu Bay",
                 "LPRO",        "Lower Prophet River",
                 "MBNK",        "Middle Banks Island",
                 "TUTR",               "Tutshi River",
                 "LNTH", "Lower North Thompson River",
                 "LPET",        "Lower Petitot River",
                 "HORS",             "Horsefly River",
                 "SETN",                 "Seton Lake",
                 "UJER",       "Upper Jennings River",
                 "CHIL",              "Chilako River",
                 "NECR",              "Nechako River",
                 "TAYR",               "Taylor River",
                 "SUST",               "Sustut River",
                 "LSKE",         "Lower Skeena River",
                 "UBIR",   "Upper Bell -Irving River",
                 "UEUT",          "Upper Eutsuk Lake",
                 "TOOD",           "Toodoggone River",
                 "UHAF",        "Upper Halfway River",
                 "STUL",                "Stuart Lake",
                 "ADMS",                "Adams River",
                 "USKE",         "Upper Skeena River",
                 "UCHR",      "Upper Chilcotin River",
                 "KETL",               "Kettle River",
                 "LTRE",       "Lower Trembleur Lake",
                 "LBTN",        "Lower Beatton River",
                 "MMUS",        "Middle Muskwa River",
                 "HARR",             "Harrison River",
                 "DRIR",            "Driftwood River",
                 "BEAV",               "Beaver River",
                 "GOLD",                 "Gold River",
                 "CHWK",           "Chilliwack River",
                 "CHIR",               "Chilko River",
                 "SANJ",             "San Juan River",
                 "FINL",               "Finlay River",
                 "KNIG",               "Knight Inlet",
                 "MFRT",   "Middle Fort Nelson River",
                 "DUNC",                "Duncan Lake",
                 "NEVI", "Northeast Vancouver Island",
                 "FROG",                 "Frog River",
                 "FINA",                 "Finlay Arm",
                 "USHU",              "Upper Shuswap",
                 "KLAR",              "Klappan River",
                 "INGR",             "Ingenika River",
                 "KITL",              "Kitlope River",
                 "LMUS",         "Lower Muskwa River",
                 "BOWR",                     "Bowron",
                 "MUSK",               "Muskeg River",
                 "CLRH",             "Columbia Reach",
                 "MSKE",        "Middle Skeena River",
                 "SAHD",            "Sahdoanah Creek",
                 "VICT",                   "Victoria",
                 "SPAT",             "Spatsizi River",
                 "LDEN",           "Lower Dean River",
                 "SMAR",             "St. Mary River",
                 "COLR",             "Columbia River",
                 "DUNE",              "Dunedin River",
                 "PINE",                 "Pine River",
                 "MPRO",       "Middle Prophet River",
                 "KAHN",              "Kahntah River",
                 "BLAR",           "Blackwater River",
                 "KISP",              "Kispiox River",
                 "PITR",               "Pitman River",
                 "FONT",               "Fontas River",
                 "BRID",               "Bridge Creek",
                 "DEAR",                "Dease River",
                 "PCEA",                  "Peace Arm",
                 "UARL",           "Upper Arrow Lake",
                 "SEYM",              "Seymour Inlet",
                 "TAKL",                 "Takla Lake",
                 "NATR",               "Nation River",
                 "LHAF",        "Lower Halfway River",
                 "FIRE",            "Firesteel River",
                 "SMOK",                "Smoky River",
                 "FRAN",              "Francois Lake",
                 "KCHL",                "Kotcho Lake",
                 "CRKD",              "Crooked River",
                 "CLWR",           "Clearwater River",
                 "TSIT",              "Tsitika River",
                 "SHEK",             "Shekilie River",
                 "MFRA",              "Middle Fraser",
                 "MORK",              "Morkill River",
                 "CARP",                  "Carp Lake",
                 "ZYMO",              "Zymoetz River",
                 "ULRD",          "Upper Liard River",
                 "PARS",              "Parsnip River",
                 "LIAR",                "Liard River",
                 "ELKR",                  "Elk River",
                 "FRCN",              "Fraser Canyon",
                 "HERR",              "Herrick Creek",
                 "HOLB",                    "Holberg",
                 "SAJR",             "San Jose River",
                 "QUES",              "Quesnel River",
                 "ISKR",                "Iskut River",
                 "LOMI",        "Lower Omineca River",
                 "UOMI",        "Upper Omineca River",
                 "TAHS",                     "Tahsis",
                 "NICL",               "Nicola River",
                 "INKR",               "Inklin River",
                 "MESC",                 "Mess Creek",
                 "UNAR",           "Upper Nass River",
                 "LKEC",        "Lower Kechika River",
                 "LKEL",                    "Lakelse",
                 "PORI",             "Porcher Island",
                 "PARK",                 "Parksville",
                 "LRDO",               "Laredo Inlet",
                 "LEUT",          "Lower Eutsuk Lake",
                 "KLIN",           "Klinaklini River",
                 "USTK",        "Upper Stikine River",
                 "CHES",            "Cheslatta River",
                 "KISK",           "Kiskatinaw River",
                 "CARR",              "Cariboo River",
                 "LISR",          "Lower Iskut River",
                 "STIR",              "Stikine River",
                 "CANO",                "Canoe Reach",
                 "MURT",                "Murtle Lake",
                 "UPET",        "Upper Petitot River",
                 "MORI",              "Morsby Island",
                 "MESI",            "Mesilinka River",
                 "KAKC",              "Kakiddi Creek",
                 "STHM",       "South Thompson River",
                 "BONP",            "Bonaparte River",
                 "SALM",               "Salmon River",
                 "NBNK",         "North Banks Island",
                 "UNRS",    "Upper Nechako Reservoir",
                 "KINR",             "Kinskuch River",
                 "OWIK",               "Owikeno Lake",
                 "TOBA",                 "Toba Inlet",
                 "COAL",                 "Coal River",
                 "OKAN",             "Okanagan River",
                 "KOTL",              "Kootenay Lake",
                 "MORR",               "Morice River",
                 "SAHT",             "Sahtaneh River",
                 "MSTR",       "Middle Stikine River",
                 "KUSR",               "Kusawa River",
                 "KHTZ",               "Khutze River",
                 "CAMB",             "Campbell River",
                 "USIK",  "Upper Sikanni Chief River",
                 "TURN",            "Turnagain River",
                 "UMUS",         "Upper Muskwa River",
                 "UFRA",         "Upper Fraser River",
                 "BLUR",                 "Blue River",
                 "BABR",               "Babine River",
                 "TSAY",              "Tsaytis River",
                 "MCGR",             "McGregor River",
                 "BRKS",           "Brooks Peninsula",
                 "SWIR",                "Swift River",
                 "MIDR",               "Middle River",
                 "BBAR",              "Big Bar Creek",
                 "LPCE",          "Lower Peace River",
                 "SQAM",                   "Squamish",
                 "SKGT",               "Skagit River",
                 "OSPK",               "Ospika River",
                 "UPCE",          "Upper Peace River",
                 "KOTR",             "Kootenay River",
                 "GRAI",              "Graham Island",
                 "COWN",                   "Cowichan",
                 "LFRA",               "Lower Fraser",
                 "BULL",                 "Bull River",
                 "KSHR",               "Kshwan River",
                 "SHUL",               "Shuswap Lake",
                 "THOM",             "Thompson River",
                 "UPRO",        "Upper Prophet River",
                 "LCHR",      "Lower Chilcotin River",
                 "BULK",              "Bulkley River",
                 "UFRT",    "Upper Fort Nelson River",
                 "TATR",         "Tatshenshini River",
                 "NIEL",                 "Niel Creek",
                 "WORC",               "Work Channel",
                 "LBIR",   "Lower Bell -Irving River",
                 "BIGC",                  "Big Creek",
                 "BELA",          "Bella Coola River",
                 "LSAL",         "Lower Salmon River",
                 "NARC",             "Narcosli Creek",
                 "REVL",            "Revelstoke Lake",
                 "LCHL",        "Lower Chilako River",
                 "LARL",           "Lower Arrow Lake",
                 "KLUM",                "Kalum River",
                 "UBTN",        "Upper Beatton River",
                 "MURR",               "Murray River",
                 "LSIK",  "Lower Sikanni Chief River",
                 "UDEN",           "Upper Dean River",
                 "LNIC",         "Lower Nicola River",
                 "NECL",       "Necleetsconnay River",
                 "GRNL",                 "Green Lake",
                 "KHOR",        "Kicking Horse River",
                 "UTRE",       "Upper Trembleur Lake",
                 "JERV",               "Jervis Inlet",
                 "MAHD",                "Mahood Lake",
                 "TABR",                "Tabor River",
                 "LNAR",           "Lower Nass River",
                 "GATA",               "Gataga River",
                 "NAZR",                "Nazko River",
                 "HAYR",                  "Hay River",
                 "MDEA",         "Middle Dease River"
  )
