restoration_principles_pb <- tibble::tribble(
                                                                              ~Principle,                                                                                                                                                                                                                                                                                                                                                                                                                     ~Description,
                                    "Target root causes of habitat and ecosystem change",                                                                                                                                                                                                                                                                                            "Aim at the main factors causing ecosystem decline. Identify and try to reverse the impact of human activities on natural processes.",
                                         "Tailor restoration actions to local potential",                                                                                                                                                                                                                                     "Each section of a river or stream has its own set of natural features due to its geographic location and climate. Design restoration efforts to align with these inherent characteristics.",
                            "Match the scale of restoration to the scale of the problem", "The restoration effort should correspond to the extent of the issue. Localized problems, such as removal of vegetation by a riverbank, need targeted solutions. However, broader impacts like floodplain alteration due to railways, highways, and intensive farming, require numerous actions across the area. Restoring habitats for species that traverse large areas needs planning that covers their entire living range.",
                                                   "Be explicit about expected outcomes",                                                                                                                         "Restoring natural areas is a slow process, and it may take time to see the results. Natural ecosystems are always changing, and a single project might not lead to immediate, noticeable improvements. Setting clear, measurable goals is crucial for understanding the impact of restoration efforts."
                            )

restoration_principles_pb_caption <- "Principles of process-based restoration adapted from Beechie et al. (2010). Developed with the aid of GPT-4 as tracked in this link https://chat.openai.com/share/fb0de9b0-0d79-40f8-aec4-a35ac14c1164."
